Lesson10 try1
ilavio/java_courses_tlt pull request #10
Opened 2021-04-27 08:20 UTC by ilavio

Студент Потемкин И.Ю.
Lesson10 Java 8 - 11

2021-04-27 16:46 UTC, tlt-java-courses requested changes

2021-04-27 16:46 UTC, tlt-java-courses commented on pom.xml
> -            <groupId>org.projectlombok</groupId>
Lombok использовать можно

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Sausage.java
> +public class Sausage {
Давай использовать lombok

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +        log.info("\nreadFileCreateSausage():");
Для чего перенос строки в логах?

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +    private static final Logger log = LoggerFactory.getLogger(SausageProcessor.class);
Давай использовать lombok

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +            List<Sausage> list = lineStream.map(element -> {
Давай использовать лямбды без блока с '{', '}' и return

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +            }).collect(Collectors.toCollection(ArrayList<Sausage>::new));
Collectors.toList

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +            printSausage(list);
Давай вызывать не стрим с логгированием, а log.info("...{}", Arrays.toString(...));

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/TaskOneOld.java
> +public class TaskOneOld {
Что есть Old?

2021-04-27 16:46 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/TaskOneNew.java
> +        if (Files.exists(path)) {
В чем сакральный смысл удаления файла, а после его создания?

2021-04-27 16:48 UTC, tlt-java-courses requested changes

2021-04-27 16:48 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/TaskOneOld.java
> +    private boolean CheckingNumber(String element) {
Название метода с заглавной буквы

2021-04-28 22:28 UTC, ilavio commented on pom.xml
> -            <groupId>org.projectlombok</groupId>
Перевел.

2021-04-28 22:29 UTC, ilavio commented on src/main/java/com/potemkin/i/Sausage.java
> +public class Sausage {
Перешел на Lombok

2021-04-28 22:30 UTC, ilavio commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +        log.info("\nreadFileCreateSausage():");
Убрал. (Подумал, что удобней смотреться будет в консоле)

2021-04-28 22:31 UTC, ilavio commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +    private static final Logger log = LoggerFactory.getLogger(SausageProcessor.class);
Перешол на Lombok

2021-04-28 22:31 UTC, ilavio commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +            List<Sausage> list = lineStream.map(element -> {
Убрал.

2021-04-28 22:31 UTC, ilavio commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +            }).collect(Collectors.toCollection(ArrayList<Sausage>::new));
Поставил

2021-04-28 22:32 UTC, ilavio commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +            printSausage(list);
Поменял.

2021-04-28 22:34 UTC, ilavio commented on src/main/java/com/potemkin/i/TaskOneNew.java
> +        if (Files.exists(path)) {
Это если запускать программу еще раз, чтобы удалился старый файл. Убрал.

2021-04-28 22:34 UTC, ilavio commented on src/main/java/com/potemkin/i/TaskOneOld.java
> +    private boolean CheckingNumber(String element) {
Исправил

2021-04-29 17:49 UTC, tlt-java-courses requested changes

2021-04-29 17:49 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Sausage.java
> +public class Sausage {
А геттеры, сеттеры, конструкторы, toString?

2021-04-29 17:49 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +        log.info("printSausage(): {}", list);
А для чего выносить одну строку лога в метод, который ты испольуешь всего один раз?

2021-05-02 10:42 UTC, ilavio commented on src/main/java/com/potemkin/i/SausageProcessor.java
> +        log.info("printSausage(): {}", list);
Изначально приследовал цель вывода столбиком. Но поптом, было замечание не использовать log в цикле forEch.
Убрал метод.

2021-05-02 10:45 UTC, ilavio commented on src/main/java/com/potemkin/i/Sausage.java
> +public class Sausage {
Добавил log's

2021-05-02 20:28 UTC, tlt-java-courses approved these changes

2021-05-02 20:28 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Sausage.java
> +public class Sausage {
Зачем логи в геттерах и сеттерах? )

2021-05-02 20:28 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Sausage.java
> +public class Sausage {
Можно было просто использовать @Data и @AllArgsConst...

2021-05-02 20:28 UTC, merged