Lesson14 JPA JDBC Liquibase
ilavio/java_courses_tlt pull request #13
Opened 2021-05-20 14:36 UTC by ilavio

Студент Потемкин И.Ю.
Lesson14 JPA JDBC Liquibase

2021-05-21 18:34 UTC, tlt-java-courses requested changes

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-db/pom.xml
> +        <liquibase.pas>pas</liquibase.pas>
pass
из-за этого не удалось раскатить скрипты

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelogv1/creatingmanytomanyorderproduct.xml
> +            CREATE TABLE potemkin.OrderProduct
Давай использовать xml теги для создания, а не sql

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelogv1/creatingmanytomanyorderproduct.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Для чего так много ченжлогов? Должен быть один кумулятивный содержащий инклюды. И один условно v1 содержащий ченжсеты первой версии БД

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelogv1/db-changelog.xml
> +    <include file="src/main/resources/db/changelogv1/creatingtablecustomer.xml"/>
Давай сделаем 1 ченжсет из этих 5... И пусть v1 будет подпапкой changelog
Ченжсетудайадекватноеназваниесразделителямиввиде-, а не вот так

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelogv1/creatingmanytomanyorderproduct.xml
> +            ProductId INTEGER REFERENCES potemkin.product (productid)
таблицы именуются с разделителем в виде '_'

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/domain/entity/SupplierTest.java
> +        assertTrue(sup.equals(suppli));
Давай разделим внутри тестов на блоки визуально переносом строки, чтобы это не было постоянно полотном текста
- Подготовки данных
- Вызов тестируемых методов
- Проверки результатов

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/domain/entity/SupplierTest.java
> +    Supplier suppli;
Модификаторы доступа?

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/domain/entity/CustomerTest.java
> +    public void equlsTest() {
А что ты тестируешь здесь в принципе?

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/MainImplTest.java
>      public void main() {
Бесполезный тест

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/CrudMyFirstTest.java
> +        sup.setCompanyName("ABIBAS");
Давай разнесем на методы внутри теста createProduct() и createSupplier() и использовать их.

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/CrudMyFirstTest.java
> +    List<Order> orders = new ArrayList<Order>();
Модификаторы....

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/resources/META-INF/persistence.xml
> +            <property name="hibernate.show_sql" value="true" />
true - хорошо для себя, но не для меня

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Supplier.java
> +    private List <Product> products = new ArrayList<Product>();
Для чего лишние указание дженерика в конкретном типе?

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Order.java
> +    @JoinTable(name = "orderproduct", joinColumns = @JoinColumn(name = "orderId", referencedColumnName = "orderId"), inverseJoinColumns = @JoinColumn(name = "productId", referencedColumnName = "produ
У меня строка в ревью не влазит, давай придерживаться клин кода

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/MainImpl.java
> +        log.info("Пуск соединения с базой данных");
Следи за красотой кода в принципе, тебе приятно полотно текста читать?

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudMyFirst.java
> +        Order or = null;
Для чего ты вынес из try объявление переменной если ты не используешь её далее?

2021-05-21 18:34 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/CrudMyFirstTest.java
> +    CrudMyFirst crud;
Такими темпами у тебя внутри крада будет создаваться энтити менеджер. Тебе нужно в тесте замокировать объект entity менеджера и передать его своему классу.

2021-05-21 18:38 UTC, tlt-java-courses requested changes
**Все замечания распространяются не только на строку где комментарий стоит, а в целом на весь соотв. код**

2021-05-21 18:38 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudMyFirst.java
> +    private EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("JPA-First");
Ты не сможешь протестировать класс из-за динамического встраивания, придется через рефлексию в тестах вставлять мог этой фактори, что будет генерить мок энтити менеджера

2021-05-21 18:38 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudMyFirst.java
> +        var entity = entityManagerFactory.createEntityManager();
entity - дезинформирует. т.к. здесь у тебя entityManager

2021-05-21 18:38 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudMyFirst.java
> +    public void addCustomer(String customerName, String phone) {
Передавай в методы уже готовый объект Customer который здесь будешь уже сохранять. Незачем в методах персистенц слоя иметь бизнесс-логику

2021-05-21 18:42 UTC, tlt-java-courses requested changes

2021-05-21 18:42 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/test/java/com/potemkin/i/CrudMyFirstTest.java
> +        crud = Mockito.mock(CrudMyFirst.class);
Тот самый кусок неправильного использования моков. Нужно мокирвать объекты что используются внутри тестируемого класса, а не сам класс

2021-05-21 21:58 UTC, ilavio commented on java_courses_tlt-db/src/main/resources/db/changelogv1/creatingmanytomanyorderproduct.xml
> +            ProductId INTEGER REFERENCES potemkin.product (productid)
Это не название таблицы а название схемы(схема.таблица)

2021-05-22 05:25 UTC, ilavio commented on java_courses_tlt-db/pom.xml
> +        <liquibase.pas>pas</liquibase.pas>
Поменял на pass

2021-05-22 05:26 UTC, ilavio commented on java_courses_tlt-db/src/main/resources/db/changelogv1/creatingmanytomanyorderproduct.xml
> +            CREATE TABLE potemkin.OrderProduct
Перешол на теги

2021-05-22 05:26 UTC, ilavio commented on java_courses_tlt-db/src/main/resources/db/changelogv1/creatingmanytomanyorderproduct.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Удалил сделал 1

2021-05-22 05:26 UTC, ilavio commented on java_courses_tlt-db/src/main/resources/db/changelogv1/db-changelog.xml
> +    <include file="src/main/resources/db/changelogv1/creatingtablecustomer.xml"/>
удалил сделал 1 и папку v1

2021-05-22 05:28 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudMyFirst.java
> +        var entity = entityManagerFactory.createEntityManager();
Переименовал

2021-05-22 14:00 UTC, tlt-java-courses requested changes

2021-05-22 14:00 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelog/db-changelog.xml
> +    <include file="src/main/resources/db/changelog/v1/creating-table.xml"/>
Чтобы в будущем сохранялся порядок создания ченжлогов в самом каталоге, лучше в начало писать условный id 1, 2 и т.д.

2021-05-22 14:00 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelog/v1/creating-table.xml
> +        author="Iliya_Potemkin">
Перенос не нужен

2021-05-22 14:00 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelog/v1/creating-table.xml
> +            <column name="customer_name" type="varchar(50)">
Когда между тегами пусто, можно писать: `<column name="customer_name" type="varchar(50)"/>`

2021-05-22 14:00 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelog/v1/creating-table.xml
> +    <changeSet id="2020-05-18_customers"
Что customers?

2021-05-22 14:00 UTC, tlt-java-courses commented on java_courses_tlt-db/src/main/resources/db/changelog/v1/creating-table.xml
> +    <changeSet id="2020-05-18_orders" author="Iliya_Potemkin">
А что orders?

2021-05-22 14:00 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudMyFirst.java
> +public CrudMyFirst(EntityManagerFactory entityManagerFactory) {
Давай использовать lombok

2021-05-23 20:08 UTC, tlt-java-courses approved these changes

2021-05-23 20:15 UTC, merged