Lesson16 Spring core
ilavio/java_courses_tlt pull request #15
Opened 2021-05-28 18:47 UTC by ilavio

Студент Потемкин И.Ю.
Lesson16 Spring core

2021-06-03 19:12 UTC, tlt-java-courses requested changes

2021-06-03 19:12 UTC, tlt-java-courses commented on pom.xml
> +                        <exclude>**/ServCustomer.class</exclude>
Лучше бы пакет с сущностями заэксклюдил, которые не нужно тестировать

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +@Scope("singleton")
Для чего указание скоупа, если он по дефолту синглтон?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +@Component("crudhandler")
Зачем указание имени компонента если оно по деелту берется от названия класса, а в твоём случае не отличается?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    public CrudHandler() {
Для чего пустой конструктор?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    private EntityManagerFactory managerFactory;
final?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    public CrudHandler(@Qualifier("entityManagerFactory") EntityManagerFactory managerFactory) {
Можно назвать переменную entityManagerFactory тогда не пришлось бы использовать квалифаер

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +public class CrudHandler {
CustomerRepository привыкай называть классы работающие с персистентным слоем так

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandlerSupAndProduct.java
> +public class CrudHandlerSupAndProduct {
Для разных сущностей - разные репозитории

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    public void addEntity(Customer customer) {
addCustomer

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +public class CrudHandler {
Где интерфейс?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandlerSupAndProduct.java
> +public class CrudHandlerSupAndProduct {
Остальные замечания из CrudHandler сюда тоже подходят

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/SinglEntityManager.java
> +public class SinglEntityManager {
А для чего синглтон?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/SinglEntityManager.java
> +    if(entityManagerFactory == null){
Приложения бывают многопоточные и данный синглтон не поддерживает это

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/Config.java
> +public interface Config {
Лишний пустой класс

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigLocal.java
> +    public Customer customer() {
Ты бинами делаешь сущности. Сущности не относятся к работе бизнес логики

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigMy.java
> +public class SpringConfigMy implements Config{
EntityManagerConfig

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigMy.java
> +@ComponentScan("com.potemkin.i")
Одного компонент скана хватит на всё приложение если в них одинаковые значения

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigMy.java
> +@PropertySource("classpath:entity.properties")
Как и одного проперти сорса

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Customer.java
> +public class Customer {
Зачем сущности бинами делать?

2021-06-03 19:12 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/service/ServiceLocal.java
> +public class ServiceLocal implements ServiceInt {
У тебя должен быть один сервис который работает с разными бинами при включении профиля. Т.е. У тебя поставщик данных зависит от профиля (из БД или захардкоженные данные), а сервис с бизнес логикой не должен меняться

2021-06-04 09:23 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/SinglEntityManager.java
> +public class SinglEntityManager {
Это было для Сервелетов. Чтобы все сервелеты использовали один manager. А здесь его не стал удалять.

2021-06-04 16:26 UTC, ilavio commented on pom.xml
> +                        <exclude>**/ServCustomer.class</exclude>
Принял.

2021-06-04 16:27 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +@Scope("singleton")
Убрал.

2021-06-04 16:31 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +@Component("crudhandler")
По началу я не знал как именно spring учитывает названия, с большой буквы или нет, или чувствителен ли к регистру. 
Убрал.

2021-06-04 16:31 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    public CrudHandler() {
Убрал. Удалил класс.

2021-06-04 16:32 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    private EntityManagerFactory managerFactory;
Сделал final.

2021-06-04 16:33 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    public CrudHandler(@Qualifier("entityManagerFactory") EntityManagerFactory managerFactory) {
Принял.

2021-06-04 16:34 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +public class CrudHandler {
Сделал репозиторий отдельный и с интерфейсом.

2021-06-04 16:34 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandlerSupAndProduct.java
> +public class CrudHandlerSupAndProduct {
Сделал репозиторий отдельный и с интерфейсом.

2021-06-04 16:35 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/CrudHandler.java
> +    public void addEntity(Customer customer) {
Переименовал.

2021-06-04 16:36 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/SinglEntityManager.java
> +public class SinglEntityManager {
Удалил класс.

2021-06-04 16:36 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/SinglEntityManager.java
> +    if(entityManagerFactory == null){
Удалил класс.

2021-06-04 16:36 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/Config.java
> +public interface Config {
Удалил.

2021-06-04 16:37 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigMy.java
> +public class SpringConfigMy implements Config{
Переименовал.

2021-06-04 16:41 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigMy.java
> +@ComponentScan("com.potemkin.i")
Я предполагал, что в зависимости от профиля (активного) бины с другим профилем не берутся за ненадобностью, а значит и значения из них.

2021-06-04 16:41 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/config/SpringConfigMy.java
> +@PropertySource("classpath:entity.properties")
Я предполагал, что в зависимости от профиля (активного) бины с другим профилем не берутся за ненадобностью, а значит и значения из них.

2021-06-04 16:42 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Customer.java
> +public class Customer {
Убрал.

2021-06-04 20:05 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/service/ServiceLocal.java
> +public class ServiceLocal implements ServiceInt {
Поменял логику. Один сервис работает с разными бинами и не зависит от профиля.

2021-06-05 07:59 UTC, tlt-java-courses requested changes

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Customer.java
> +    public String getOrders() {
Геттер листа строкой? Зачем?

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Customer.java
> +    public String toString() {
Используй ломбок. А лист ордеров просто заэкслюдь с помощью того же ломбока

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +public class CustomerRepository implements CustomerR {
CustomerRepositoryImpl, а интерфейс CustomerRepository

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    private final EntityManagerFactory MANAGER_FACTORY;
Только константы пишутся в UPPER_CAMEL_CASE

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    public void addCustomer(Customer customer) {
Репозитории должны возвращать результат своей деятельности

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    public Customer parseForCustomer(JSONObject json) {
Парсинг из json не должен происходить на уровне (persistance) приложения работы с БД. Это уровень API

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    public void deleteCust(int customerId) {
delete метод может возвращать boolean - успешность удаления

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +@Component()
Скобочки можно убирать у пустых аннотаций, глаза режут

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/hard/CustRepHard.java
> +public class CustRepHard implements CustomerR {
ПрстНаимКЛас НеочЧит 😐

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/interf/CustomerR.java
> +public interface CustomerR {
JavaDocs?

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/service/ServiceCrud.java
> +    CustomerR repoCust;
Private final
И автоваер через контруктор, который генерируется lombok

2021-06-05 07:59 UTC, tlt-java-courses commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/service/ServiceLocal.java
> +public class ServiceLocal  {
Лишний класс

2021-06-05 07:59 UTC, tlt-java-courses commented on pom.xml
> +                        <exclude>**/ServCustomer.class</exclude>
Пакет, а не каждый отдельный класс )

2021-06-05 07:59 UTC, tlt-java-courses commented on pom.xml
> +                        <exclude>**/CustomerR.class</exclude>
Репозитории для чего эксклюд?

2021-06-05 08:54 UTC, ilavio commented on pom.xml
> +                        <exclude>**/CustomerR.class</exclude>
Так это интерфейс. Зачем его проверять?

2021-06-05 15:43 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Customer.java
> +    public String getOrders() {
Из-за JSON. Когда он сканирует get методы и получается зацикливание. Т.К. в Order есть Customer.

2021-06-05 16:10 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/domain/entity/Customer.java
> +    public String toString() {
@ToString(exclude = "orders") Добавил.

2021-06-05 16:51 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    private final EntityManagerFactory MANAGER_FACTORY;
Исправил.

2021-06-05 16:51 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +public class CustomerRepository implements CustomerR {
Исправил.

2021-06-05 17:13 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    public void addCustomer(Customer customer) {
Теперь возвращают.

2021-06-05 17:13 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/interf/CustomerR.java
> +public interface CustomerR {
Добавил.

2021-06-05 17:14 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +    public void deleteCust(int customerId) {
добавил

2021-06-05 17:16 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/CustomerRepository.java
> +@Component()
Убрал.

2021-06-05 17:20 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/repository/hard/CustRepHard.java
> +public class CustRepHard implements CustomerR {
Переименовал.

2021-06-05 17:28 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/service/ServiceCrud.java
> +    CustomerR repoCust;
Добавил.

2021-06-05 17:28 UTC, ilavio commented on java_courses_tlt-impl/src/main/java/com/potemkin/i/service/ServiceLocal.java
> +public class ServiceLocal  {
Удалил.

2021-06-05 20:11 UTC, merged

2021-06-05 20:42 UTC, tlt-java-courses commented
1. В DB модуле отсутствуют liquibase скрипты
![image](https://user-images.githubusercontent.com/75726498/120904817-42369c00-c65f-11eb-91eb-eaca2f311ac2.png)
2. Запуск приложения приводит к ошибке
![image](https://user-images.githubusercontent.com/75726498/120904831-59758980-c65f-11eb-8d74-1e39b67827ae.png)
3. Получение в сущности заместо листа - строки. Считаю некорректным и необоснованным решением
![image](https://user-images.githubusercontent.com/75726498/120904858-8c1f8200-c65f-11eb-8d65-22d24dfcb3e9.png)
4.
![image](https://user-images.githubusercontent.com/75726498/120904918-d1dc4a80-c65f-11eb-82fc-38fa80816e8f.png)
5. Некорректное взаимодействие слоёв в архитектуре приложения
![image](https://user-images.githubusercontent.com/75726498/120904930-ef111900-c65f-11eb-9418-153b1569ad38.png)
6. Отсутствие тестов на большую часть кода
![image](https://user-images.githubusercontent.com/75726498/120904941-051ed980-c660-11eb-9aea-3cc5929838a2.png)

7. Несоблюдение клин кода
7.1. Лишние классы 
![image](https://user-images.githubusercontent.com/75726498/120904843-6d20f000-c65f-11eb-9dc3-a6f9caf03be0.png)
7.2. Лишний код 
![image](https://user-images.githubusercontent.com/75726498/120904866-9c376180-c65f-11eb-8b08-16774fc73420.png)
7.3. Неговорящие наименования классов
![image](https://user-images.githubusercontent.com/75726498/120904888-af4a3180-c65f-11eb-9178-de10ccc6f86f.png)
7.4. Нарушение компоновки приложения
![image](https://user-images.githubusercontent.com/75726498/120904907-bec97a80-c65f-11eb-9478-1a2085900ee2.png)