Lesson8 try1
ilavio/java_courses_tlt pull request #8
Opened 2021-04-18 14:11 UTC by ilavio

Студент Потемкин И.Ю.
Lesson8 Clean code

2021-04-18 19:52 UTC, tlt-java-courses requested changes
Нет демонстрации работы приложения

Замечания:
- Форматирование кода
  - Отступы, переносы и форматирование кода и файлов (таб = 4 пробела)
  - Некорректные пути пакетов
  - Бесполезные переменные в коде
  - Отсутвие { и }
- Проблемы в коде
  - Много ненужных конструкторов Эксепшенов которые не испольуются в коде
  - Тестирование эксепшенов путем их прямого создания, а не вызова из кода
  - Излишнее использование переменных в коде. Рекомендую заумываться о необходимости переменных и поиска оптимизации кода
  - Использование Raw типов для generic классов
- JavaDoc
  - Много лишнего в содержании JavaDoc говорит о том, что код не самодокументирующий. Переменные, конструкторы. Допустим зачем мне знать это: `Кроме того, этот класс переопределяет методы: toString(), hashCode(),
 * equals().` - эти вещи по умолчанию должны быть.
  - Старайся не допускать орфографических ошибок в JavaDoc

Рекомендации:
- Можно использовать lombok

2021-04-19 18:45 UTC, tlt-java-courses requested changes
Замечания: 
- Почему в логах время выполнения отсутсвует? 
- В INFO логах очень много мусора. Необходимо разнести по DEBUG и TRACE уровню.

2021-04-19 18:45 UTC, tlt-java-courses commented on pom.xml
> +	<profiles>
В файлах до сих пор отступы некорректные

2021-04-19 18:45 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/CacheElement.java
> +        if (this == obj)
Нет фигурных скобок

2021-04-19 18:45 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/CallChekedException.java
> +        } catch (NoSuchFieldException e) {
Пустые catch блоки

2021-04-19 18:45 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Main.java
> +        log.info("Содержимое cache: {}", cashe.toString());
toString в логах вызывается автоматически. Причем на 29 строке ты это используешь правильно

2021-04-19 18:45 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Storage.java
> +/*
Копирайт конечно хорошо. Но в данном случае он некорректный.

2021-04-19 18:45 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Storage.java
> +		this.storage = new Object[10];
Формат Табов

2021-04-19 18:45 UTC, tlt-java-courses commented on src/test/java/com/potemkin/i/CacheElementTest.java
> +		this.cachEl = new CacheElement<String>(1, "T");
И здесь табы

2021-04-20 06:30 UTC, ilavio commented on src/main/java/com/potemkin/i/CacheElement.java
> +        if (this == obj)
добавил

2021-04-20 06:31 UTC, ilavio commented on src/main/java/com/potemkin/i/CallChekedException.java
> +        } catch (NoSuchFieldException e) {
Исправил

2021-04-20 06:31 UTC, ilavio commented on src/main/java/com/potemkin/i/Main.java
> +        log.info("Содержимое cache: {}", cashe.toString());
Убрал

2021-04-20 06:31 UTC, ilavio commented on src/main/java/com/potemkin/i/Storage.java
> +/*
Удалил

2021-04-20 06:32 UTC, ilavio commented on src/main/java/com/potemkin/i/Storage.java
> +		this.storage = new Object[10];
Убрал

2021-04-20 06:32 UTC, ilavio commented on src/test/java/com/potemkin/i/CacheElementTest.java
> +		this.cachEl = new CacheElement<String>(1, "T");
Убрал

2021-04-20 06:33 UTC, ilavio commented on pom.xml
> +	<profiles>
Исправил на пробелы

2021-04-20 19:47 UTC, tlt-java-courses approved these changes

2021-04-20 19:47 UTC, merged