Lesson9 Reflection Annotation
ilavio/java_courses_tlt pull request #9
Opened 2021-04-22 18:38 UTC by ilavio

Студент Потемкин И.Ю.
Lesson9 Reflection Annotation

2021-04-23 06:44 UTC, tlt-java-courses requested changes

2021-04-23 06:44 UTC, tlt-java-courses commented on pom.xml
> +    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Мне кажется я вижу эти изменения второй раз, может стоит внести изменения в master ветку?

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/Value.java
> +    int age() default 0;
А если я в сущности добавлю еще с десяток - два полей, мне придется для каждого поля аннотацию обновлять?

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Human.java
> +    public void setName(@Value(name = "Foma") String name) {
Сделай чтобы Value вешалась на метод, а не на параметр

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +    public static void start(Object object) {
Чем обосновывается то, что все методы - статик?

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/exception/NoValueAnnotationException.java
> +public class NoValueAnnotationException extends Exception {
JavaDoc?

2021-04-23 06:44 UTC, tlt-java-courses commented on src/test/java/com/potemkin/i/ClassAnalyzerTest.java
> +public class ClassAnalyzerTest {
JavaDoc на публичных классах должен быть.

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/exception/NoValueAnnotationException.java
> +        super("Отсутствует значение поля");
По заданию ошибка предполагала, что есть сущность с аннотацией Entity, но без Value аннотации.

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                } catch (IllegalAccessException e) {
Почему не сделать inline если обработка в catch блоках одинаковая?

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +    private static void assignmentOfValuesFields(Field field, String valueStr, int valueInt, Object object) {
А еще, если я добавлю полей в сущности мне придётся методы обновлять?

2021-04-23 06:44 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                        } catch (IllegalArgumentException e) {
Почему не inline?

2021-04-23 20:06 UTC, ilavio commented on pom.xml
> +    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Возможно это еще из за того, что я пропускаю через Format после вставки текста из репозитория maven.

2021-04-23 20:07 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/Value.java
> +    int age() default 0;
Пересмотрел логику аннотации.

2021-04-23 20:08 UTC, ilavio commented on src/main/java/com/potemkin/i/Human.java
> +    public void setName(@Value(name = "Foma") String name) {
Перенес. Хотя мне было тежелей добраться до параметра метода не жели до метода.

2021-04-23 20:09 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +    public static void start(Object object) {
Из за конференции. Решил так же сделать статичным как на уроке. Поменял.

2021-04-23 20:09 UTC, ilavio commented on src/main/java/com/potemkin/i/exception/NoValueAnnotationException.java
> +public class NoValueAnnotationException extends Exception {
Добавил.

2021-04-23 20:10 UTC, ilavio commented on src/test/java/com/potemkin/i/ClassAnalyzerTest.java
> +public class ClassAnalyzerTest {
В тестах добавил.

2021-04-23 20:10 UTC, ilavio commented on src/main/java/com/potemkin/i/exception/NoValueAnnotationException.java
> +        super("Отсутствует значение поля");
Изменил.

2021-04-23 20:11 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                } catch (IllegalAccessException e) {
Сделал.

2021-04-23 20:13 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +    private static void assignmentOfValuesFields(Field field, String valueStr, int valueInt, Object object) {
Пересмотрел логику внедрения значений. А так же добавил конвертацию до нужного типа, принимаемого объектом.

2021-04-23 20:13 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                        } catch (IllegalArgumentException e) {
изменил.

2021-04-24 07:13 UTC, tlt-java-courses requested changes

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Human.java
> +    @Value(value = "18")
Если указывается одно лишь value, то не обязательно ключевое слово указывать.

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Main.java
> +    public static void main(String[] args) {
Не увидел демонстрации пунктов 3, 4.а, 4.b

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/Value.java
> +    String value() default "no name";
А если повежу аннотацию на Boolean или Integer. Код не сломается и они заполнятся дефолтными значениями?

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/Value.java
> +    String referenceToValue() default "no reference";
А корректно ли будет, если я задам в файле значение `no reference`, но путь указывать в pojo не буду. Оно случаем не считает это значение?

2021-04-24 07:13 UTC, tlt-java-courses commented on src/test/java/com/potemkin/i/HumanTest.java
> + * HumanTest
Не информтивный JavaDoc

2021-04-24 07:13 UTC, tlt-java-courses commented on src/test/java/com/potemkin/i/MainTest.java
> + * MainTest
Не информативный JavaDoc

2021-04-24 07:13 UTC, tlt-java-courses commented on src/test/java/com/potemkin/i/StudentTest.java
> + * StudentTest
Не информативный JavaDoc

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                } catch (IOException e) {
2 catch блока, которые можно inline обрабатывать

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +     * метод анализа полей объекта
Орфографию и пунктуацию нужно соблюдать в JavaDoc. С заглавной буквы с точкой в конце.

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +     * @param object
Описание параметра

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                log.info("annotationHandlerValueField внедряемое значение: {} ; referenceToValue - {}",
Давай, чтобы указать, что это метод вызываемый, делать лог формата: `annotationHandlerValueField() - ...`, а то сейчас это не очевидно

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/Main.java
> +    static final Logger logRoot = LogManager.getRootLogger();
Лучше использовать LogFactory из пакета slf4j

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                        log.debug("Ошибка в annotationHandlerValueField : ", e);
1. debug лог в секции перехвата ошибок. log.error(...)
2. `annotationHandlerValueField() - error`

2021-04-24 07:13 UTC, tlt-java-courses commented on src/main/resources/file.txt
> +{age1=234}
Если файл предполагает решение пунктов 8 и 9, то файл некорректен

2021-04-24 10:01 UTC, ilavio commented on src/main/resources/file.txt
> +{age1=234}
Внес изменея в файл

2021-04-24 10:01 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                        log.debug("Ошибка в annotationHandlerValueField : ", e);
Изменил на error

2021-04-24 10:03 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                log.info("annotationHandlerValueField внедряемое значение: {} ; referenceToValue - {}",
добавил()

2021-04-24 10:03 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +     * @param object
Описал

2021-04-24 10:07 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +     * метод анализа полей объекта
Исправил на заглавную

2021-04-24 10:13 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/ClassAnalyzer.java
> +                } catch (IOException e) {
IOException это предок (обобщенный) класс FileNotFoundException. И если их я пытаюсь поставить в одну линию то IDE просит удалить из этой линии FileNotFoundException.

2021-04-24 10:14 UTC, ilavio commented on src/test/java/com/potemkin/i/StudentTest.java
> + * StudentTest
Дописал. Но кратко.

2021-04-24 10:14 UTC, ilavio commented on src/test/java/com/potemkin/i/MainTest.java
> + * MainTest
Дописал. Но кратко.

2021-04-24 10:14 UTC, ilavio commented on src/test/java/com/potemkin/i/HumanTest.java
> + * HumanTest
Дописал. Но кратко.

2021-04-24 10:22 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/Value.java
> +    String referenceToValue() default "no reference";
Вставил проверку на "no reference"

2021-04-24 10:24 UTC, ilavio commented on src/main/java/com/potemkin/i/annotations/Value.java
> +    String value() default "no name";
В демонстрации я навесил аннотацию и на boolean, и double, и на Integer

2021-04-24 10:25 UTC, ilavio commented on src/main/java/com/potemkin/i/Main.java
> +    public static void main(String[] args) {
Добавил исключение. И продемонстрировал

2021-04-24 10:29 UTC, ilavio commented on src/main/java/com/potemkin/i/Human.java
> +    @Value(value = "18")
Вставил без value.

2021-04-24 21:09 UTC, merged